# Generated by Django 4.0.5 on 2022-06-27 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0002_profilefeed'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProfileFeed',
            new_name='ProfileFeedItem',
        ),
    ]
